### ISSUE TITLE
courgette-jvm version : 5.0.0 on click of test, test result is not displayed 

### ISSUE THREAD

**Issue by LearningPur** [prashant-ramcharan/courgette-jvm#201]
Hi @prashant-ramcharan I have recently upgraded courgette-jvm version to "5.0.0" and noticed "courgette-report" on click of any test it doesn't display any test result.

Please find attached small video clip inside below zip folder to understand an issue

[issue video clip.zip](https://github.com/prashant-ramcharan/courgette-jvm/files/5120964/issue.video.clip.zip)

Here is what i see in network call 

<img width="1537" alt="Screen Shot 2020-08-24 at 9 00 00 PM" src="https://user-images.githubusercontent.com/57417403/91114141-ced21980-e64c-11ea-92b8-7555be4ed23a.png">

**Comment by prashant-ramcharan** [comment]
Hi @LearningPur 

This is now resolved. Thanks for reporting.

**Comment by LearningPur** [comment]
Thanks for quick fix @prashant-ramcharan 

I still see version 5.0.0, do you yet need to push the changes to make it available with new version ?

**Comment by prashant-ramcharan** [comment]
As this was a CDN issue it did not require a new release.

**Comment by LearningPur** [comment]
Thanks for confirming @prashant-ramcharan
