### ISSUE TITLE
Error while importing the file for input string : \"1,473.309\"'"

### ISSUE THREAD

**Issue by KannanPandi** [prashant-ramcharan/courgette-jvm#270]
Hi Ram,

Once the execution is completed ,for report portal integration ,courgette report portal service is trying to import the report file , but we are getting this courgette error **{"errorCode":40035,"message":"Error while importing the file for input string : \"1,473.309\"'"}** , because of this sometime we are unable to integrate our execution with report portal 

![image](https://user-images.githubusercontent.com/59192407/112032467-6acfef00-8b62-11eb-8350-78a89ad6ddc3.png)

**Comment by prashant-ramcharan** [comment]
Hello,

Can you please share your `cucumber.xml` ?

**Comment by prashant-ramcharan** [comment]
Can you please share your `cucumber.xml` ?

**Comment by prashant-ramcharan** [comment]
Seems to be related to https://github.com/reportportal/reportportal/issues/1279 which is fixed in report portal version `5.4`

What version of report portal server are you using?

Also, can you please provide your `cucumber.xml` ?

**Comment by prashant-ramcharan** [comment]
Closing issue. 

Please re-open if you still face the same problem after upgrading to report portal version 5.4 or if you can provide your cucumber.xml for me to investigate further.

**Comment by rujutashinde** [comment]
I am using Reportportal version Build: 5.7.2
and this issue is still present 

following issue is seen when i use the `launch/import api`
`https://<instance>/api/v1/<project>/launch/import`

error:
{
  "errorCode": 40035,
  "message": "Error while importing the file. 'For input string: \"3,000.457\"'"
}

this is the  snippet from my xml which is causing the issue
```
<testcase name="testNotification" classname="io.debezium.connector.oracle.IncrementalSnapshotCaseSensitiveIT" time="3,000.457">
<error message="Index 868 out of bounds for length 868" type="java.lang.IndexOutOfBoundsException">
<![CDATA[ java.lang.IndexOutOfBoundsException: Index 868 out of bounds for length 868 at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) at java.base/java.util.Objects.checkIndex(Objects.java:359) at java.base/java.util.ArrayList.get(ArrayList.java:427) at io.debezium.pipeline.source.snapshot.incremental.AbstractIncrementalSnapshotTest.testNotification(AbstractIncrementalSnapshotTest.java:1144) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.base/java.lang.reflect.Method.invoke(Method.java:568) at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59) at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56) at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26) at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27) at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61) at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306) at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100) at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366) at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103) at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63) at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331) at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79) at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329) at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66) at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293) at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306) at org.junit.runners.ParentRunner.run(ParentRunner.java:413) at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:377) at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:284) at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:248) at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:167) at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456) at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169) at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595) at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581) ]]>
</error>
<system-out>
...
</system-out>
```
The launch is seen on the RP instance as forever waiting, and it has to be forcefully ended.

Is there a documentation on what is the format that is expected for the time field int he xunit file?

**Comment by rujutashinde** [comment]
i filed a new issue https://github.com/reportportal/reportportal/issues/2008 as i was not able to reopen this one
